Styleguide
E2E-Squad/Web pull request #15
Opened 2022-02-06 17:30 UTC by Deegoh

Add Onclick to btn

2022-02-09 11:25 UTC, loichu requested changes
Si t'arrives à faire ces 2-3 changements c'est cool sinon je m'en charge

2022-02-09 11:25 UTC, loichu commented on components/Atoms/Button/Button.md
> +<Button url="#" styleClass="btn--danger">Danger</Button>
Ici tu aurais pu utiliser `(j,t)sx padded` pour les avoir côte à côte espacés

2022-02-09 11:25 UTC, loichu commented on components/Atoms/Button/Button.tsx
> +    const btnHandle = (event: React.MouseEvent<HTMLButtonElement>) => {
Cette fonction devrait être passée en `prop` depuis le parent dans `interface types`

2022-02-09 11:26 UTC, loichu commented on components/Atoms/Button/Button.md
> +<Button url="#" styleClass="btn--danger">Danger</Button>
https://github.com/styleguidist/react-styleguidist/blob/master/docs/Documenting.md#usage-examples-and-readme-files

2022-02-09 11:29 UTC, loichu commented on components/Atoms/Button/Button.tsx
> +    const btnHandle = (event: React.MouseEvent<HTMLButtonElement>) => {
https://www.pluralsight.com/guides/typescript-pass-function-react dans ce style là mais la prop passée à `Button` peut s'appeler aussi `onClick` par souci de constance.

2022-02-16 17:18 UTC, Deegoh commented
J'ai fait les modifs demandé selon la doc

2022-02-17 16:08 UTC, loichu approved these changes
Nice !

2022-02-18 16:15 UTC, MarJC5 reviewed
LGTM

2022-02-18 16:15 UTC, MarJC5 commented on components/Atoms/Button/Button.tsx
> -            url={style[`${props.url}`]}
Petite question @Deegoh , est-ce que le button va agir comment un` <a href=""></a>` ? Parce que théoriquement c'est pas une balise link non ?

2022-02-18 16:16 UTC, MarJC5 approved these changes

2022-02-18 16:21 UTC, Deegoh commented on components/Atoms/Button/Button.tsx
> -            url={style[`${props.url}`]}
J'ai retiré la prop url. Le handle du btn est à mettre dans le parent pour le fonctionnement du btn.

2022-02-18 17:26 UTC, merged